name: Build Release Binary

permissions:
  contents: write

on:
  release:
    types: [created, published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scanner_code

    strategy:
      matrix:
        include:
          - target: "arm-unknown-linux-gnueabihf"
            name: "raspberry-pi"
          - target: "x86_64-apple-darwin"
            name: "mac-apple-silicon"
          - target: "aarch64-apple-darwin"
            name: "mac-intel"

    steps:
      - uses: actions/checkout@v3

      - name: install cross
        run: cargo install cross --git "https://github.com/cross-rs/cross"

      - name: build
        run: cross build --release --target ${{ matrix.target }}

      - uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ matrix.name }}
          file: "scanner_code/target/${{ matrix.target }}/release/scanner_code"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
